# Generated by Django 5.0.3 on 2024-03-20 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_rename_todo_name_todo_task_todo_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
