# Generated by Django 5.0.3 on 2024-03-23 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0007_todo_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='due_date_modified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='todo',
            name='due_date',
            field=models.DateTimeField(),
        ),
    ]
