# Generated by Django 5.0.3 on 2024-03-23 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0009_alter_todo_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='due_date_modified',
        ),
        migrations.AlterField(
            model_name='todo',
            name='due_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
